### ISSUE TITLE
Looks like this package doesn't work anymore

### ISSUE THREAD

**Issue by RothAndrew** [mim-Armand/aws-profiles#1]
The class SharedIniFile doesn't exist anymore in `aws-sdk`

**Comment by mim-Armand** [comment]
Yeah, it looks like they change the name of the file! ( in addition to APIs )
The file was called `shared_ini`, but now it's a folder called `shared-ini` with index files in it.
The interesting thing is that all the tests are passing ( probably because a fixed version `2.205.0` is used during the tests ), so I didn't notice the issue!
But it's a good opportunity to update to the latest SDK so I'll try to update the package, if it didn't work I'll fix the version number dor now and that should solve the issue
Thank you for bringing this up @RothAndrew

**Comment by mim-Armand** [comment]
@RothAndrew The problem should be solved,
Please update to version `1.1.0` ( by running `npm update --save get-aws-profiles`) and try again, if you had any issues please let me know.

best,
- mim

**Comment by RothAndrew** [comment]
Thanks!
